# .github/workflows/larastan.yml

name: Larastan

on:
  push:
    branches:
      - main  # Change to your main branch name if different

jobs:
  larastan:
    runs-on: ubuntu-latest

    steps:

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'  # Change to your PHP version

      - name: Install dependencies
        run: composer install

      - name: Run Larastan
        run: composer run larastan
